default['docker']['bind_uri']       = 'tcp://0.0.0.0:4243'
default['docker']['options']        = '-g=/var/lib/docker'
default['docker']['exec_driver']    = 'lxc'
default['docker']['storage_driver'] = 'aufs'
default['dokku']['version']         = '0.2.2'
